SHELL := /bin/sh

export PATH := $(HOME)/go/bin:$(PATH)

SUBSYSTEMS := $(sort $(notdir $(wildcard subsystems/*)))
BIN_DIR := bin
MODULE := github.com/Manu343726/toolbox
# The framework's own API contract. It lives under a canonical package path so
# its import name is unambiguous to every subsystem that implements it.
FRAMEWORK_PROTO_DIR := pkg/api/proto
FRAMEWORK_PROTO := $(FRAMEWORK_PROTO_DIR)/toolbox/api/v1/api.proto

.PHONY: all build test test-short fmt vet clean proto proto-tools host check-tests

all: build

# Generate the framework's own API introspection contract. Feature contracts
# are generated by each subsystem's Makefile.
proto: $(FRAMEWORK_PROTO)
	@command -v protoc >/dev/null || (echo "protoc is required" >&2; exit 1)
	@command -v protoc-gen-go >/dev/null || (echo "run 'make proto-tools' first" >&2; exit 1)
	@command -v protoc-gen-connect-go >/dev/null || (echo "run 'make proto-tools' first" >&2; exit 1)
	protoc --proto_path=$(FRAMEWORK_PROTO_DIR) --go_out=. --go_opt=module=$(MODULE) --connect-go_out=. --connect-go_opt=module=$(MODULE) toolbox/api/v1/api.proto

# Build each independent subsystem through its own Makefile.
build:
	@mkdir -p $(BIN_DIR)
	@for subsystem in $(SUBSYSTEMS); do \
		if [ -d subsystems/$$subsystem/cmd ]; then \
			$(MAKE) -C subsystems/$$subsystem build; \
			cp subsystems/$$subsystem/bin/$$subsystem $(BIN_DIR)/$$subsystem; \
		fi; \
	done
	@$(MAKE) -C cmd/toolbox build
	@cp cmd/toolbox/bin/toolbox $(BIN_DIR)/toolbox

host:
	@$(MAKE) -C cmd/toolbox build

check-tests:
	@for subsystem in $(SUBSYSTEMS); do \
		if [ -z "$$(find subsystems/$$subsystem -maxdepth 1 -name '*_test.go' -print -quit)" ]; then \
			echo "subsystem $$subsystem has no unit tests" >&2; \
			exit 1; \
		fi; \
	done

test: check-tests
	@for subsystem in $(SUBSYSTEMS); do \
		$(MAKE) -C subsystems/$$subsystem test; \
	done
	@$(MAKE) -C cmd/toolbox test
	@go test -count=1 ./...

test-short: check-tests
	@for subsystem in $(SUBSYSTEMS); do \
		$(MAKE) -C subsystems/$$subsystem test-short; \
	done
	@$(MAKE) -C cmd/toolbox test
	@go test -short -count=1 ./...

# The repository's own shape, which no package's tests can see from inside a
# package. Two things live here:
#
#   - a Go file whose package clause does not match its directory's is listed by
#     Go under IgnoredGoFiles and never compiled. The build passes, the tests
#     pass, and a file written to register a subsystem's contract has never run.
#   - a build output beside the source rather than in a bin/ directory, which is
#     where `go build .` leaves it and where a committed binary is one `git add`
#     away from being committed by whoever runs it next.
#
# `make test` runs this too, because it is part of ./... . It is a target of its
# own so that either check can be run on its own, and so that CI can name it.
check-repo:
	@go test -count=1 ./internal/repocheck

fmt:
	@gofmt -w $$(find pkg -name '*.go' -not -name '*.pb.go' -not -name '*.connect.go')
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem fmt; done
	@$(MAKE) -C cmd/toolbox fmt

vet:
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem vet; done
	@$(MAKE) -C cmd/toolbox vet
	@go vet ./...

proto-tools:
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem proto-tools; done

clean:
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem clean; done
	@$(MAKE) -C cmd/toolbox clean
	find pkg -type f \( -name '*.pb.go' -o -name '*.connect.go' \) -delete
	find pkg -name '*.pb' -delete
	rm -rf $(BIN_DIR)
