SHELL := /bin/sh

export PATH := $(HOME)/go/bin:$(PATH)

SUBSYSTEMS := $(sort $(notdir $(wildcard subsystems/*)))
BIN_DIR := bin
MODULE := github.com/Manu343726/toolbox
# The framework's own contracts, the ones a provider subsystem implements rather
# than the ones a subsystem owns. They live under canonical package paths so
# their import names are unambiguous to every subsystem that implements them, and
# in root packages so a provider depends on the root module and not on the
# aggregator it serves.
#
# Every one of them is generated in one protoc invocation, because a subsystem
# that implements two of them could otherwise be asked to build against one that
# has not been generated yet.
FRAMEWORK_PROTO_DIR := pkg/api/proto
FRAMEWORK_PROTO_FILES := toolbox/api/v1/api.proto
FRAMEWORK_SKILLS_PROTO_DIR := pkg/skills/proto
FRAMEWORK_SKILLS_PROTO_FILES := toolbox/skills/v1/skill.proto
FRAMEWORK_PROTOS := $(FRAMEWORK_PROTO_FILES:%=$(FRAMEWORK_PROTO_DIR)/%) $(FRAMEWORK_SKILLS_PROTO_FILES:%=$(FRAMEWORK_SKILLS_PROTO_DIR)/%)

.PHONY: all build test test-short fmt vet clean proto subsystems-proto proto-tools host check-tests check-repo

all: build

# Generate the framework's own contracts: the extension points a provider
# subsystem implements. Feature contracts are generated by each subsystem's own
# Makefile.
proto: $(FRAMEWORK_PROTOS)
	@command -v protoc >/dev/null || (echo "protoc is required" >&2; exit 1)
	@command -v protoc-gen-go >/dev/null || (echo "run 'make proto-tools' first" >&2; exit 1)
	@command -v protoc-gen-connect-go >/dev/null || (echo "run 'make proto-tools' first" >&2; exit 1)
	protoc --proto_path=$(FRAMEWORK_PROTO_DIR) --go_out=. --go_opt=module=$(MODULE) --connect-go_out=. --connect-go_opt=module=$(MODULE) $(FRAMEWORK_PROTO_FILES)
	protoc --proto_path=$(FRAMEWORK_SKILLS_PROTO_DIR) --go_out=. --go_opt=module=$(MODULE) --connect-go_out=. --connect-go_opt=module=$(MODULE) $(FRAMEWORK_SKILLS_PROTO_FILES)

# Generate every subsystem's own contract.
#
# Not one subsystem's build can run before another's generated packages exist, and
# every subsystem's is in a different module: each imports registryv1, so a checkout
# that has generated only the contract being built has no code to compile. The order
# is therefore all of generation before any of compilation, which is why this is a
# target of its own rather than a prerequisite threaded through each subsystem's
# Makefile.
#
# It is also why the CI matrix can test a subsystem on its own: that job generates
# this module's contracts and its dependencies' first, with the workspace disabled so
# the rest resolve to the local directories rather than to published versions.
subsystems-proto:
	@for subsystem in $(SUBSYSTEMS); do \
		if grep -qE '^proto:' subsystems/$$subsystem/Makefile 2>/dev/null; then \
			$(MAKE) -C subsystems/$$subsystem proto || exit 1; \
		fi; \
	done

# Build each independent subsystem through its own Makefile.
#
# The framework's own contract is generated first, and not only for its own sake: a
# subsystem imports the root module's generated packages, so a checkout that has
# never run protoc cannot build any of them. The order is the whole content of this
# target — root contract, then every subsystem, then the host that composes them —
# and a subsystem whose build fails stops the run rather than being skipped, because
# the copy after it is what reports a subsystem as built.
build: proto subsystems-proto
	@mkdir -p $(BIN_DIR)
	@for subsystem in $(SUBSYSTEMS); do \
		if [ -d subsystems/$$subsystem/cmd ]; then \
			$(MAKE) -C subsystems/$$subsystem build || exit 1; \
			cp subsystems/$$subsystem/bin/$$subsystem $(BIN_DIR)/$$subsystem || exit 1; \
		fi; \
	done
	@$(MAKE) -C cmd/toolbox build
	@cp cmd/toolbox/bin/toolbox $(BIN_DIR)/toolbox

host: proto subsystems-proto
	@$(MAKE) -C cmd/toolbox build

check-tests:
	@for subsystem in $(SUBSYSTEMS); do \
		if [ -z "$$(find subsystems/$$subsystem -maxdepth 1 -name '*_test.go' -print -quit)" ]; then \
			echo "subsystem $$subsystem has no unit tests" >&2; \
			exit 1; \
		fi; \
	done

# A subsystem test needs the framework's own generated packages, so the root
# contract comes first for the same reason it does in build.
test: check-tests proto subsystems-proto
	@for subsystem in $(SUBSYSTEMS); do \
		$(MAKE) -C subsystems/$$subsystem test || exit 1; \
	done
	@$(MAKE) -C cmd/toolbox test
	@go test -count=1 ./...

test-short: check-tests proto subsystems-proto
	@for subsystem in $(SUBSYSTEMS); do \
		$(MAKE) -C subsystems/$$subsystem test-short || exit 1; \
	done
	@$(MAKE) -C cmd/toolbox test
	@go test -short -count=1 ./...

# The repository's own shape, which no package's tests can see from inside a
# package. Two things live here:
#
#   - a Go file whose package clause does not match its directory's is listed by
#     Go under IgnoredGoFiles and never compiled. The build passes, the tests
#     pass, and a file written to register a subsystem's contract has never run.
#   - a build output beside the source rather than in a bin/ directory, which is
#     where `go build .` leaves it and where a committed binary is one `git add`
#     away from being committed by whoever runs it next.
#
# `make test` runs this too, because it is part of ./... . It is a target of its
# own so that either check can be run on its own, and so that CI can name it.
check-repo:
	@go test -count=1 ./internal/repocheck

fmt:
	@gofmt -w $$(find pkg -name '*.go' -not -name '*.pb.go' -not -name '*.connect.go')
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem fmt; done
	@$(MAKE) -C cmd/toolbox fmt

vet: proto subsystems-proto
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem vet; done
	@$(MAKE) -C cmd/toolbox vet
	@go vet ./...

proto-tools:
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem proto-tools; done

clean:
	@for subsystem in $(SUBSYSTEMS); do $(MAKE) -C subsystems/$$subsystem clean; done
	@$(MAKE) -C cmd/toolbox clean
	find pkg -type f \( -name '*.pb.go' -o -name '*.connect.go' \) -delete
	find pkg -name '*.pb' -delete
	rm -rf $(BIN_DIR)
