package core

import (
	"context"
	"fmt"

	"connectrpc.com/connect"
)

// Constructor is the shape generated by protoc-gen-connect-go for a typed
// service client. Keeping this as a generic function means each subsystem can
// bind its own generated client without the core package importing any
// feature protocol.
type Constructor[T any] func(connect.HTTPClient, string, ...connect.ClientOption) T

// Bind resolves a service and constructs its generated, type-safe ConnectRPC
// client. This is the service-to-service equivalent of dotfilesd's pattern:
// resolve the endpoint first, then call the generated constructor.
//
// The constructor is supplied by the caller, so the core package remains
// independent of every subsystem's protobuf contract.
func Bind[T any](ctx context.Context, client *Client, serviceName string, constructor Constructor[T], options ...connect.ClientOption) (T, error) {
	var zero T
	if client == nil {
		return zero, fmt.Errorf("cannot bind %q with a nil core client", serviceName)
	}
	if constructor == nil {
		return zero, fmt.Errorf("cannot bind %q with a nil constructor", serviceName)
	}
	endpoint, err := client.Resolve(ctx, serviceName)
	if err != nil {
		return zero, err
	}
	connectOptions := append([]connect.ClientOption(nil), client.connectOptions...)
	connectOptions = append(connectOptions, options...)
	return constructor(client.httpClient, endpoint.URL, connectOptions...), nil
}
